FROM jamierajewski/rat-container:base-root6

RUN cd /home/software && \
    wget https://root.cern/download/root_v6.20.06.Linux-ubuntu20-x86_64-gcc9.3.tar.gz && \
    tar xzfv root_v6.20.06.Linux-ubuntu20-x86_64-gcc9.3.tar.gz && \
    rm -rf root_v6.20.06.Linux-ubuntu20-x86_64-gcc9.3.tar.gz

# Set up the environment when entering the container
ENTRYPOINT ["docker-entrypoint.sh"]
